### ISSUE TITLE
Apify "This Actor is under maintenance"

### ISSUE THREAD

**Issue by slukas99** [lhotanok/zalando-scraper#1]
Hello Kristýna,

I wanted to use your Zalando scraper, but when I executed the code to retrieve the results in Python, I got no response. On the Apify page of the project, it says "This Actor is under maintenance". Can you give an estimate when the scraper can be used again/ is it still being maintained? 

Thank you for your help.

Best,
Lukas

**Comment by lhotanok** [comment]
Hello @slukas99,

Thanks for letting me know!
The scraper should be working again 🔧

For now, I only did a 'hot fix'. Over time, I'd like to make the actor more generic as it currently relies on Zalando's GraphQL IDs which are unstable and need to be updated regularly.
